apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: edgedelta
  name: agent-updater-roles
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]