entities:
- id: '{{ .k8s.secrets.edgedelta.ed-api-key }}'
  image: edgedelta
  paths:
  - edgedelta:ds/edgedelta:spec.template.spec.containers[0].image
api:
  base_url: '{{ .env.ED_API_URL }}'
  latest_tag:
    endpoint: '{{ .env.ED_LATEST_TAG_ENDPOINT }}'
    auth:
      header_key: X-ED-Config-Id
      header_value: '{{ .k8s.secrets.edgedelta.ed-api-key }}'
  log_upload:
    method: PUSH
    encoding: json
    compression: gzip
    params:
      query:
        size: '{{ .ctx.size }}'
    presigned_upload_url:
      endpoint: '/get_upload_link'
  
