entities:
- id: 111-222-333
  image: some-agent
  paths:
  - default:ds/my-agent:spec.template.spec.containers[0].image
log:
  custom_tags:
    host: '{{ .env.KUBE_POD }}'
api:
  base_url: http://localhost:8080
  auth:
    header_key: Authorization
    header_value: 'Some_token'
  latest_tag:
    endpoint: /latest-version
  metadata:
    endpoint: /metadata
  log_upload:
    enabled: true
    method: PUT
    encoding:
      type: raw
      options:
        delimiter: '\n'
    compression: gzip
    presigned_upload_url:
      endpoint: /log-upload-link
      params:
        query:
          size: '{{ .ctx.size }}'
          format: json
          compression: gzip
