name: Test and deploy

on:
  push:
    branches:
      - ozansz/actions
    tags:
      - 'v*.*.*'
    
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - uses: ko-build/setup-ko@v0.6
      - name: Run tests
        run: go test -v ./...
      - name: Deploy
        run: |
          echo "Current tag: ${{  github.ref_name }}"